// AUTO-GENERATED by scripts/generate-demo-dataset.mjs — do not edit by hand.
//
// Illustrative, at-scale sample for the public /demo page. This is SYNTHETIC and is NOT
// real measured analytics, and it is never written to the production database. It exists
// only to demonstrate what Munchr's demand intelligence looks like at a deployed-fleet scale.
// We store the precomputed report (not raw events) to keep the bundle small.
// Regenerate with: node scripts/generate-demo-dataset.mjs [scale]

export const sampleMeta = {
  "academicYear": "2025–26",
  "label": "Aug 2025 – May 2026",
  "scale": 100,
  "totalEvents": 37000,
  "searchEvents": 22000,
  "uniqueSessions": 2750,
  "note": "Illustrative at-scale sample — synthetic, not real measured analytics."
};

export const sampleReport = {
  "config": {
    "avgVendPrice": 2.5,
    "conversionRate": 1,
    "minSearchesForRec": 3,
    "thinStockThreshold": 2
  },
  "headline": {
    "totalSearches": 22000,
    "uniqueSessions": 2750,
    "machineViews": 8000,
    "directionsClicks": 2800,
    "totalUnmetSearches": 4507,
    "noResultRate": 0.20486363636363636,
    "estimatedLostRevenue": 11268,
    "totalRequests": 1200
  },
  "topSearches": [
    {
      "product": "Celsius",
      "count": 2681
    },
    {
      "product": "Doritos",
      "count": 1793
    },
    {
      "product": "Gatorade",
      "count": 1479
    },
    {
      "product": "Water",
      "count": 1299
    },
    {
      "product": "Coca Cola",
      "count": 1192
    },
    {
      "product": "Cheez It",
      "count": 956
    },
    {
      "product": "Monster",
      "count": 929
    },
    {
      "product": "Starbucks",
      "count": 906
    },
    {
      "product": "Powerade",
      "count": 891
    },
    {
      "product": "Bubly",
      "count": 829
    }
  ],
  "unmetProducts": [
    {
      "product": "Prime",
      "count": 1163,
      "machinesStocking": 0
    },
    {
      "product": "Alani",
      "count": 931,
      "machinesStocking": 0
    },
    {
      "product": "Red Bull",
      "count": 790,
      "machinesStocking": 0
    },
    {
      "product": "Takis",
      "count": 552,
      "machinesStocking": 0
    },
    {
      "product": "Liquid Death",
      "count": 477,
      "machinesStocking": 0
    },
    {
      "product": "Muscle Milk",
      "count": 317,
      "machinesStocking": 0
    },
    {
      "product": "Kombucha",
      "count": 277,
      "machinesStocking": 0
    }
  ],
  "topRequests": [
    {
      "product": "Prime",
      "count": 216,
      "machinesStocking": 0
    },
    {
      "product": "Alani",
      "count": 216,
      "machinesStocking": 0
    },
    {
      "product": "Takis",
      "count": 136,
      "machinesStocking": 0
    },
    {
      "product": "Red Bull",
      "count": 118,
      "machinesStocking": 0
    },
    {
      "product": "Celsius",
      "count": 102,
      "machinesStocking": 22
    },
    {
      "product": "Muscle Milk",
      "count": 99,
      "machinesStocking": 0
    },
    {
      "product": "Gatorade",
      "count": 94,
      "machinesStocking": 35
    },
    {
      "product": "Liquid Death",
      "count": 93,
      "machinesStocking": 0
    },
    {
      "product": "Kombucha",
      "count": 70,
      "machinesStocking": 0
    },
    {
      "product": "Bubly",
      "count": 56,
      "machinesStocking": 2
    }
  ],
  "thinlyStocked": [
    {
      "product": "Bubly",
      "count": 829,
      "machinesStocking": 2
    },
    {
      "product": "Sunkist",
      "count": 722,
      "machinesStocking": 2
    }
  ],
  "topBuildings": [
    {
      "building": "Perkins Library",
      "count": 1030
    },
    {
      "building": "Levine Science Research Center",
      "count": 847
    },
    {
      "building": "Bryan Center",
      "count": 732
    },
    {
      "building": "Broadhead Center",
      "count": 604
    },
    {
      "building": "Physics Building",
      "count": 473
    },
    {
      "building": "Nello L. Teer Building",
      "count": 452
    },
    {
      "building": "Bell Tower Residence Hall",
      "count": 447
    },
    {
      "building": "Randolph Residence Hall",
      "count": 422
    },
    {
      "building": "Few Quad",
      "count": 382
    },
    {
      "building": "Wilson Recreation Center",
      "count": 344
    }
  ],
  "topDirections": [
    {
      "building": "Perkins Library",
      "count": 366
    },
    {
      "building": "Levine Science Research Center",
      "count": 283
    },
    {
      "building": "Bryan Center",
      "count": 243
    },
    {
      "building": "Broadhead Center",
      "count": 240
    },
    {
      "building": "Physics Building",
      "count": 164
    }
  ],
  "byHour": [
    {
      "hour": 0,
      "count": 783
    },
    {
      "hour": 1,
      "count": 754
    },
    {
      "hour": 2,
      "count": 632
    },
    {
      "hour": 3,
      "count": 57
    },
    {
      "hour": 4,
      "count": 56
    },
    {
      "hour": 5,
      "count": 93
    },
    {
      "hour": 6,
      "count": 267
    },
    {
      "hour": 7,
      "count": 546
    },
    {
      "hour": 8,
      "count": 886
    },
    {
      "hour": 9,
      "count": 979
    },
    {
      "hour": 10,
      "count": 1083
    },
    {
      "hour": 11,
      "count": 1303
    },
    {
      "hour": 12,
      "count": 1470
    },
    {
      "hour": 13,
      "count": 1270
    },
    {
      "hour": 14,
      "count": 1189
    },
    {
      "hour": 15,
      "count": 1254
    },
    {
      "hour": 16,
      "count": 1397
    },
    {
      "hour": 17,
      "count": 1492
    },
    {
      "hour": 18,
      "count": 1696
    },
    {
      "hour": 19,
      "count": 1520
    },
    {
      "hour": 20,
      "count": 1267
    },
    {
      "hour": 21,
      "count": 1001
    },
    {
      "hour": 22,
      "count": 1235
    },
    {
      "hour": 23,
      "count": 970
    }
  ],
  "itemBreakdowns": [
    {
      "product": "Celsius",
      "total": 2783,
      "unmet": 0,
      "requested": 102,
      "machinesStocking": 22,
      "topBuildings": [
        {
          "building": "Perkins Library",
          "count": 376
        },
        {
          "building": "Levine Science Research Center",
          "count": 310
        },
        {
          "building": "Bryan Center",
          "count": 218
        },
        {
          "building": "Broadhead Center",
          "count": 196
        },
        {
          "building": "Physics Building",
          "count": 177
        },
        {
          "building": "Nello L. Teer Building",
          "count": 159
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 120
        },
        {
          "hour": 1,
          "count": 93
        },
        {
          "hour": 2,
          "count": 90
        },
        {
          "hour": 3,
          "count": 6
        },
        {
          "hour": 4,
          "count": 8
        },
        {
          "hour": 5,
          "count": 9
        },
        {
          "hour": 6,
          "count": 33
        },
        {
          "hour": 7,
          "count": 48
        },
        {
          "hour": 8,
          "count": 109
        },
        {
          "hour": 9,
          "count": 108
        },
        {
          "hour": 10,
          "count": 153
        },
        {
          "hour": 11,
          "count": 132
        },
        {
          "hour": 12,
          "count": 190
        },
        {
          "hour": 13,
          "count": 147
        },
        {
          "hour": 14,
          "count": 156
        },
        {
          "hour": 15,
          "count": 154
        },
        {
          "hour": 16,
          "count": 151
        },
        {
          "hour": 17,
          "count": 189
        },
        {
          "hour": 18,
          "count": 202
        },
        {
          "hour": 19,
          "count": 150
        },
        {
          "hour": 20,
          "count": 139
        },
        {
          "hour": 21,
          "count": 125
        },
        {
          "hour": 22,
          "count": 145
        },
        {
          "hour": 23,
          "count": 126
        }
      ]
    },
    {
      "product": "Doritos",
      "total": 1793,
      "unmet": 0,
      "requested": 0,
      "machinesStocking": 58,
      "topBuildings": [
        {
          "building": "Perkins Library",
          "count": 230
        },
        {
          "building": "Levine Science Research Center",
          "count": 190
        },
        {
          "building": "Bryan Center",
          "count": 149
        },
        {
          "building": "Broadhead Center",
          "count": 140
        },
        {
          "building": "Randolph Residence Hall",
          "count": 102
        },
        {
          "building": "Nello L. Teer Building",
          "count": 98
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 62
        },
        {
          "hour": 1,
          "count": 54
        },
        {
          "hour": 2,
          "count": 37
        },
        {
          "hour": 3,
          "count": 3
        },
        {
          "hour": 4,
          "count": 2
        },
        {
          "hour": 5,
          "count": 9
        },
        {
          "hour": 6,
          "count": 21
        },
        {
          "hour": 7,
          "count": 54
        },
        {
          "hour": 8,
          "count": 64
        },
        {
          "hour": 9,
          "count": 76
        },
        {
          "hour": 10,
          "count": 89
        },
        {
          "hour": 11,
          "count": 113
        },
        {
          "hour": 12,
          "count": 108
        },
        {
          "hour": 13,
          "count": 105
        },
        {
          "hour": 14,
          "count": 94
        },
        {
          "hour": 15,
          "count": 88
        },
        {
          "hour": 16,
          "count": 117
        },
        {
          "hour": 17,
          "count": 128
        },
        {
          "hour": 18,
          "count": 116
        },
        {
          "hour": 19,
          "count": 117
        },
        {
          "hour": 20,
          "count": 105
        },
        {
          "hour": 21,
          "count": 71
        },
        {
          "hour": 22,
          "count": 90
        },
        {
          "hour": 23,
          "count": 70
        }
      ]
    },
    {
      "product": "Gatorade",
      "total": 1573,
      "unmet": 0,
      "requested": 94,
      "machinesStocking": 35,
      "topBuildings": [
        {
          "building": "Perkins Library",
          "count": 207
        },
        {
          "building": "Levine Science Research Center",
          "count": 162
        },
        {
          "building": "Broadhead Center",
          "count": 147
        },
        {
          "building": "Bryan Center",
          "count": 131
        },
        {
          "building": "Physics Building",
          "count": 97
        },
        {
          "building": "Bell Tower Residence Hall",
          "count": 83
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 50
        },
        {
          "hour": 1,
          "count": 63
        },
        {
          "hour": 2,
          "count": 37
        },
        {
          "hour": 3,
          "count": 8
        },
        {
          "hour": 4,
          "count": 2
        },
        {
          "hour": 5,
          "count": 6
        },
        {
          "hour": 6,
          "count": 16
        },
        {
          "hour": 7,
          "count": 36
        },
        {
          "hour": 8,
          "count": 65
        },
        {
          "hour": 9,
          "count": 69
        },
        {
          "hour": 10,
          "count": 62
        },
        {
          "hour": 11,
          "count": 95
        },
        {
          "hour": 12,
          "count": 86
        },
        {
          "hour": 13,
          "count": 86
        },
        {
          "hour": 14,
          "count": 84
        },
        {
          "hour": 15,
          "count": 99
        },
        {
          "hour": 16,
          "count": 94
        },
        {
          "hour": 17,
          "count": 95
        },
        {
          "hour": 18,
          "count": 106
        },
        {
          "hour": 19,
          "count": 117
        },
        {
          "hour": 20,
          "count": 71
        },
        {
          "hour": 21,
          "count": 77
        },
        {
          "hour": 22,
          "count": 82
        },
        {
          "hour": 23,
          "count": 67
        }
      ]
    },
    {
      "product": "Prime",
      "total": 1379,
      "unmet": 1163,
      "requested": 216,
      "machinesStocking": 0,
      "topBuildings": [
        {
          "building": "Perkins Library",
          "count": 30
        },
        {
          "building": "Levine Science Research Center",
          "count": 21
        },
        {
          "building": "Bryan Center",
          "count": 18
        },
        {
          "building": "Randolph Residence Hall",
          "count": 16
        },
        {
          "building": "Physics Building",
          "count": 14
        },
        {
          "building": "Few Quad",
          "count": 13
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 43
        },
        {
          "hour": 1,
          "count": 55
        },
        {
          "hour": 2,
          "count": 44
        },
        {
          "hour": 3,
          "count": 2
        },
        {
          "hour": 4,
          "count": 3
        },
        {
          "hour": 5,
          "count": 3
        },
        {
          "hour": 6,
          "count": 15
        },
        {
          "hour": 7,
          "count": 47
        },
        {
          "hour": 8,
          "count": 50
        },
        {
          "hour": 9,
          "count": 60
        },
        {
          "hour": 10,
          "count": 57
        },
        {
          "hour": 11,
          "count": 74
        },
        {
          "hour": 12,
          "count": 76
        },
        {
          "hour": 13,
          "count": 85
        },
        {
          "hour": 14,
          "count": 82
        },
        {
          "hour": 15,
          "count": 64
        },
        {
          "hour": 16,
          "count": 73
        },
        {
          "hour": 17,
          "count": 79
        },
        {
          "hour": 18,
          "count": 92
        },
        {
          "hour": 19,
          "count": 106
        },
        {
          "hour": 20,
          "count": 74
        },
        {
          "hour": 21,
          "count": 59
        },
        {
          "hour": 22,
          "count": 69
        },
        {
          "hour": 23,
          "count": 67
        }
      ]
    },
    {
      "product": "Water",
      "total": 1299,
      "unmet": 0,
      "requested": 0,
      "machinesStocking": 52,
      "topBuildings": [
        {
          "building": "Perkins Library",
          "count": 180
        },
        {
          "building": "Levine Science Research Center",
          "count": 147
        },
        {
          "building": "Broadhead Center",
          "count": 111
        },
        {
          "building": "Bryan Center",
          "count": 104
        },
        {
          "building": "Nello L. Teer Building",
          "count": 84
        },
        {
          "building": "Physics Building",
          "count": 79
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 35
        },
        {
          "hour": 1,
          "count": 40
        },
        {
          "hour": 2,
          "count": 32
        },
        {
          "hour": 3,
          "count": 1
        },
        {
          "hour": 4,
          "count": 5
        },
        {
          "hour": 5,
          "count": 7
        },
        {
          "hour": 6,
          "count": 9
        },
        {
          "hour": 7,
          "count": 22
        },
        {
          "hour": 8,
          "count": 46
        },
        {
          "hour": 9,
          "count": 55
        },
        {
          "hour": 10,
          "count": 55
        },
        {
          "hour": 11,
          "count": 71
        },
        {
          "hour": 12,
          "count": 82
        },
        {
          "hour": 13,
          "count": 66
        },
        {
          "hour": 14,
          "count": 62
        },
        {
          "hour": 15,
          "count": 86
        },
        {
          "hour": 16,
          "count": 96
        },
        {
          "hour": 17,
          "count": 81
        },
        {
          "hour": 18,
          "count": 112
        },
        {
          "hour": 19,
          "count": 91
        },
        {
          "hour": 20,
          "count": 71
        },
        {
          "hour": 21,
          "count": 49
        },
        {
          "hour": 22,
          "count": 71
        },
        {
          "hour": 23,
          "count": 54
        }
      ]
    },
    {
      "product": "Coca Cola",
      "total": 1192,
      "unmet": 0,
      "requested": 0,
      "machinesStocking": 47,
      "topBuildings": [
        {
          "building": "Perkins Library",
          "count": 148
        },
        {
          "building": "Levine Science Research Center",
          "count": 141
        },
        {
          "building": "Bryan Center",
          "count": 123
        },
        {
          "building": "Broadhead Center",
          "count": 91
        },
        {
          "building": "Physics Building",
          "count": 87
        },
        {
          "building": "Social Sciences Building",
          "count": 61
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 33
        },
        {
          "hour": 1,
          "count": 43
        },
        {
          "hour": 2,
          "count": 27
        },
        {
          "hour": 3,
          "count": 4
        },
        {
          "hour": 4,
          "count": 4
        },
        {
          "hour": 5,
          "count": 7
        },
        {
          "hour": 6,
          "count": 13
        },
        {
          "hour": 7,
          "count": 26
        },
        {
          "hour": 8,
          "count": 48
        },
        {
          "hour": 9,
          "count": 45
        },
        {
          "hour": 10,
          "count": 51
        },
        {
          "hour": 11,
          "count": 74
        },
        {
          "hour": 12,
          "count": 74
        },
        {
          "hour": 13,
          "count": 65
        },
        {
          "hour": 14,
          "count": 62
        },
        {
          "hour": 15,
          "count": 68
        },
        {
          "hour": 16,
          "count": 92
        },
        {
          "hour": 17,
          "count": 88
        },
        {
          "hour": 18,
          "count": 79
        },
        {
          "hour": 19,
          "count": 85
        },
        {
          "hour": 20,
          "count": 57
        },
        {
          "hour": 21,
          "count": 40
        },
        {
          "hour": 22,
          "count": 65
        },
        {
          "hour": 23,
          "count": 42
        }
      ]
    },
    {
      "product": "Alani",
      "total": 1147,
      "unmet": 931,
      "requested": 216,
      "machinesStocking": 0,
      "topBuildings": [
        {
          "building": "Perkins Library",
          "count": 31
        },
        {
          "building": "Bryan Center",
          "count": 27
        },
        {
          "building": "Physics Building",
          "count": 17
        },
        {
          "building": "Levine Science Research Center",
          "count": 16
        },
        {
          "building": "Broadhead Center",
          "count": 15
        },
        {
          "building": "Social Sciences Building",
          "count": 14
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 49
        },
        {
          "hour": 1,
          "count": 48
        },
        {
          "hour": 2,
          "count": 27
        },
        {
          "hour": 3,
          "count": 2
        },
        {
          "hour": 4,
          "count": 0
        },
        {
          "hour": 5,
          "count": 7
        },
        {
          "hour": 6,
          "count": 17
        },
        {
          "hour": 7,
          "count": 27
        },
        {
          "hour": 8,
          "count": 37
        },
        {
          "hour": 9,
          "count": 52
        },
        {
          "hour": 10,
          "count": 67
        },
        {
          "hour": 11,
          "count": 54
        },
        {
          "hour": 12,
          "count": 76
        },
        {
          "hour": 13,
          "count": 59
        },
        {
          "hour": 14,
          "count": 50
        },
        {
          "hour": 15,
          "count": 61
        },
        {
          "hour": 16,
          "count": 70
        },
        {
          "hour": 17,
          "count": 73
        },
        {
          "hour": 18,
          "count": 73
        },
        {
          "hour": 19,
          "count": 68
        },
        {
          "hour": 20,
          "count": 64
        },
        {
          "hour": 21,
          "count": 54
        },
        {
          "hour": 22,
          "count": 59
        },
        {
          "hour": 23,
          "count": 53
        }
      ]
    },
    {
      "product": "Cheez It",
      "total": 956,
      "unmet": 0,
      "requested": 0,
      "machinesStocking": 51,
      "topBuildings": [
        {
          "building": "Levine Science Research Center",
          "count": 126
        },
        {
          "building": "Perkins Library",
          "count": 105
        },
        {
          "building": "Bryan Center",
          "count": 85
        },
        {
          "building": "Broadhead Center",
          "count": 82
        },
        {
          "building": "Physics Building",
          "count": 71
        },
        {
          "building": "Randolph Residence Hall",
          "count": 50
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 31
        },
        {
          "hour": 1,
          "count": 24
        },
        {
          "hour": 2,
          "count": 29
        },
        {
          "hour": 3,
          "count": 1
        },
        {
          "hour": 4,
          "count": 3
        },
        {
          "hour": 5,
          "count": 1
        },
        {
          "hour": 6,
          "count": 8
        },
        {
          "hour": 7,
          "count": 24
        },
        {
          "hour": 8,
          "count": 37
        },
        {
          "hour": 9,
          "count": 36
        },
        {
          "hour": 10,
          "count": 38
        },
        {
          "hour": 11,
          "count": 52
        },
        {
          "hour": 12,
          "count": 82
        },
        {
          "hour": 13,
          "count": 50
        },
        {
          "hour": 14,
          "count": 42
        },
        {
          "hour": 15,
          "count": 50
        },
        {
          "hour": 16,
          "count": 57
        },
        {
          "hour": 17,
          "count": 63
        },
        {
          "hour": 18,
          "count": 75
        },
        {
          "hour": 19,
          "count": 65
        },
        {
          "hour": 20,
          "count": 44
        },
        {
          "hour": 21,
          "count": 51
        },
        {
          "hour": 22,
          "count": 54
        },
        {
          "hour": 23,
          "count": 39
        }
      ]
    },
    {
      "product": "Monster",
      "total": 929,
      "unmet": 0,
      "requested": 0,
      "machinesStocking": 11,
      "topBuildings": [
        {
          "building": "Perkins Library",
          "count": 117
        },
        {
          "building": "Levine Science Research Center",
          "count": 96
        },
        {
          "building": "Bryan Center",
          "count": 77
        },
        {
          "building": "Broadhead Center",
          "count": 64
        },
        {
          "building": "Bell Tower Residence Hall",
          "count": 63
        },
        {
          "building": "Physics Building",
          "count": 60
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 39
        },
        {
          "hour": 1,
          "count": 42
        },
        {
          "hour": 2,
          "count": 27
        },
        {
          "hour": 3,
          "count": 4
        },
        {
          "hour": 4,
          "count": 3
        },
        {
          "hour": 5,
          "count": 4
        },
        {
          "hour": 6,
          "count": 11
        },
        {
          "hour": 7,
          "count": 14
        },
        {
          "hour": 8,
          "count": 35
        },
        {
          "hour": 9,
          "count": 34
        },
        {
          "hour": 10,
          "count": 37
        },
        {
          "hour": 11,
          "count": 52
        },
        {
          "hour": 12,
          "count": 64
        },
        {
          "hour": 13,
          "count": 56
        },
        {
          "hour": 14,
          "count": 37
        },
        {
          "hour": 15,
          "count": 51
        },
        {
          "hour": 16,
          "count": 48
        },
        {
          "hour": 17,
          "count": 63
        },
        {
          "hour": 18,
          "count": 69
        },
        {
          "hour": 19,
          "count": 60
        },
        {
          "hour": 20,
          "count": 47
        },
        {
          "hour": 21,
          "count": 29
        },
        {
          "hour": 22,
          "count": 49
        },
        {
          "hour": 23,
          "count": 54
        }
      ]
    },
    {
      "product": "Red Bull",
      "total": 908,
      "unmet": 790,
      "requested": 118,
      "machinesStocking": 0,
      "topBuildings": [
        {
          "building": "Bryan Center",
          "count": 13
        },
        {
          "building": "Perkins Library",
          "count": 13
        },
        {
          "building": "Broadhead Center",
          "count": 13
        },
        {
          "building": "Levine Science Research Center",
          "count": 12
        },
        {
          "building": "Nello L. Teer Building",
          "count": 10
        },
        {
          "building": "Allen Building",
          "count": 8
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 35
        },
        {
          "hour": 1,
          "count": 28
        },
        {
          "hour": 2,
          "count": 22
        },
        {
          "hour": 3,
          "count": 1
        },
        {
          "hour": 4,
          "count": 4
        },
        {
          "hour": 5,
          "count": 2
        },
        {
          "hour": 6,
          "count": 10
        },
        {
          "hour": 7,
          "count": 23
        },
        {
          "hour": 8,
          "count": 44
        },
        {
          "hour": 9,
          "count": 37
        },
        {
          "hour": 10,
          "count": 44
        },
        {
          "hour": 11,
          "count": 49
        },
        {
          "hour": 12,
          "count": 47
        },
        {
          "hour": 13,
          "count": 57
        },
        {
          "hour": 14,
          "count": 52
        },
        {
          "hour": 15,
          "count": 43
        },
        {
          "hour": 16,
          "count": 29
        },
        {
          "hour": 17,
          "count": 55
        },
        {
          "hour": 18,
          "count": 69
        },
        {
          "hour": 19,
          "count": 56
        },
        {
          "hour": 20,
          "count": 56
        },
        {
          "hour": 21,
          "count": 40
        },
        {
          "hour": 22,
          "count": 60
        },
        {
          "hour": 23,
          "count": 45
        }
      ]
    },
    {
      "product": "Starbucks",
      "total": 906,
      "unmet": 0,
      "requested": 0,
      "machinesStocking": 13,
      "topBuildings": [
        {
          "building": "Perkins Library",
          "count": 125
        },
        {
          "building": "Levine Science Research Center",
          "count": 101
        },
        {
          "building": "Bryan Center",
          "count": 77
        },
        {
          "building": "Broadhead Center",
          "count": 65
        },
        {
          "building": "Physics Building",
          "count": 57
        },
        {
          "building": "Bell Tower Residence Hall",
          "count": 48
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 36
        },
        {
          "hour": 1,
          "count": 26
        },
        {
          "hour": 2,
          "count": 29
        },
        {
          "hour": 3,
          "count": 1
        },
        {
          "hour": 4,
          "count": 6
        },
        {
          "hour": 5,
          "count": 3
        },
        {
          "hour": 6,
          "count": 11
        },
        {
          "hour": 7,
          "count": 15
        },
        {
          "hour": 8,
          "count": 29
        },
        {
          "hour": 9,
          "count": 33
        },
        {
          "hour": 10,
          "count": 38
        },
        {
          "hour": 11,
          "count": 43
        },
        {
          "hour": 12,
          "count": 55
        },
        {
          "hour": 13,
          "count": 46
        },
        {
          "hour": 14,
          "count": 52
        },
        {
          "hour": 15,
          "count": 58
        },
        {
          "hour": 16,
          "count": 57
        },
        {
          "hour": 17,
          "count": 53
        },
        {
          "hour": 18,
          "count": 80
        },
        {
          "hour": 19,
          "count": 70
        },
        {
          "hour": 20,
          "count": 51
        },
        {
          "hour": 21,
          "count": 28
        },
        {
          "hour": 22,
          "count": 46
        },
        {
          "hour": 23,
          "count": 40
        }
      ]
    },
    {
      "product": "Powerade",
      "total": 891,
      "unmet": 0,
      "requested": 0,
      "machinesStocking": 14,
      "topBuildings": [
        {
          "building": "Perkins Library",
          "count": 110
        },
        {
          "building": "Levine Science Research Center",
          "count": 105
        },
        {
          "building": "Broadhead Center",
          "count": 93
        },
        {
          "building": "Bryan Center",
          "count": 82
        },
        {
          "building": "Nello L. Teer Building",
          "count": 51
        },
        {
          "building": "Physics Building",
          "count": 49
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 29
        },
        {
          "hour": 1,
          "count": 21
        },
        {
          "hour": 2,
          "count": 33
        },
        {
          "hour": 3,
          "count": 2
        },
        {
          "hour": 4,
          "count": 0
        },
        {
          "hour": 5,
          "count": 3
        },
        {
          "hour": 6,
          "count": 7
        },
        {
          "hour": 7,
          "count": 22
        },
        {
          "hour": 8,
          "count": 31
        },
        {
          "hour": 9,
          "count": 44
        },
        {
          "hour": 10,
          "count": 38
        },
        {
          "hour": 11,
          "count": 58
        },
        {
          "hour": 12,
          "count": 54
        },
        {
          "hour": 13,
          "count": 44
        },
        {
          "hour": 14,
          "count": 41
        },
        {
          "hour": 15,
          "count": 44
        },
        {
          "hour": 16,
          "count": 53
        },
        {
          "hour": 17,
          "count": 63
        },
        {
          "hour": 18,
          "count": 86
        },
        {
          "hour": 19,
          "count": 41
        },
        {
          "hour": 20,
          "count": 51
        },
        {
          "hour": 21,
          "count": 30
        },
        {
          "hour": 22,
          "count": 54
        },
        {
          "hour": 23,
          "count": 42
        }
      ]
    },
    {
      "product": "Bubly",
      "total": 885,
      "unmet": 0,
      "requested": 56,
      "machinesStocking": 2,
      "topBuildings": [
        {
          "building": "Perkins Library",
          "count": 114
        },
        {
          "building": "Levine Science Research Center",
          "count": 88
        },
        {
          "building": "Bryan Center",
          "count": 80
        },
        {
          "building": "Broadhead Center",
          "count": 71
        },
        {
          "building": "Bell Tower Residence Hall",
          "count": 56
        },
        {
          "building": "Physics Building",
          "count": 51
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 31
        },
        {
          "hour": 1,
          "count": 25
        },
        {
          "hour": 2,
          "count": 27
        },
        {
          "hour": 3,
          "count": 0
        },
        {
          "hour": 4,
          "count": 2
        },
        {
          "hour": 5,
          "count": 5
        },
        {
          "hour": 6,
          "count": 13
        },
        {
          "hour": 7,
          "count": 23
        },
        {
          "hour": 8,
          "count": 31
        },
        {
          "hour": 9,
          "count": 45
        },
        {
          "hour": 10,
          "count": 42
        },
        {
          "hour": 11,
          "count": 47
        },
        {
          "hour": 12,
          "count": 61
        },
        {
          "hour": 13,
          "count": 40
        },
        {
          "hour": 14,
          "count": 48
        },
        {
          "hour": 15,
          "count": 46
        },
        {
          "hour": 16,
          "count": 55
        },
        {
          "hour": 17,
          "count": 45
        },
        {
          "hour": 18,
          "count": 61
        },
        {
          "hour": 19,
          "count": 75
        },
        {
          "hour": 20,
          "count": 54
        },
        {
          "hour": 21,
          "count": 41
        },
        {
          "hour": 22,
          "count": 44
        },
        {
          "hour": 23,
          "count": 24
        }
      ]
    },
    {
      "product": "Snickers",
      "total": 817,
      "unmet": 0,
      "requested": 0,
      "machinesStocking": 53,
      "topBuildings": [
        {
          "building": "Levine Science Research Center",
          "count": 97
        },
        {
          "building": "Perkins Library",
          "count": 94
        },
        {
          "building": "Broadhead Center",
          "count": 75
        },
        {
          "building": "Bryan Center",
          "count": 68
        },
        {
          "building": "Bell Tower Residence Hall",
          "count": 55
        },
        {
          "building": "Randolph Residence Hall",
          "count": 48
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 28
        },
        {
          "hour": 1,
          "count": 21
        },
        {
          "hour": 2,
          "count": 23
        },
        {
          "hour": 3,
          "count": 3
        },
        {
          "hour": 4,
          "count": 4
        },
        {
          "hour": 5,
          "count": 4
        },
        {
          "hour": 6,
          "count": 12
        },
        {
          "hour": 7,
          "count": 20
        },
        {
          "hour": 8,
          "count": 32
        },
        {
          "hour": 9,
          "count": 30
        },
        {
          "hour": 10,
          "count": 33
        },
        {
          "hour": 11,
          "count": 63
        },
        {
          "hour": 12,
          "count": 51
        },
        {
          "hour": 13,
          "count": 42
        },
        {
          "hour": 14,
          "count": 44
        },
        {
          "hour": 15,
          "count": 38
        },
        {
          "hour": 16,
          "count": 43
        },
        {
          "hour": 17,
          "count": 52
        },
        {
          "hour": 18,
          "count": 72
        },
        {
          "hour": 19,
          "count": 42
        },
        {
          "hour": 20,
          "count": 49
        },
        {
          "hour": 21,
          "count": 36
        },
        {
          "hour": 22,
          "count": 46
        },
        {
          "hour": 23,
          "count": 29
        }
      ]
    },
    {
      "product": "Sunkist",
      "total": 722,
      "unmet": 0,
      "requested": 0,
      "machinesStocking": 2,
      "topBuildings": [
        {
          "building": "Perkins Library",
          "count": 105
        },
        {
          "building": "Levine Science Research Center",
          "count": 79
        },
        {
          "building": "Bryan Center",
          "count": 73
        },
        {
          "building": "Broadhead Center",
          "count": 60
        },
        {
          "building": "Physics Building",
          "count": 45
        },
        {
          "building": "Bell Tower Residence Hall",
          "count": 40
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 15
        },
        {
          "hour": 1,
          "count": 19
        },
        {
          "hour": 2,
          "count": 18
        },
        {
          "hour": 3,
          "count": 4
        },
        {
          "hour": 4,
          "count": 0
        },
        {
          "hour": 5,
          "count": 2
        },
        {
          "hour": 6,
          "count": 12
        },
        {
          "hour": 7,
          "count": 15
        },
        {
          "hour": 8,
          "count": 22
        },
        {
          "hour": 9,
          "count": 40
        },
        {
          "hour": 10,
          "count": 23
        },
        {
          "hour": 11,
          "count": 39
        },
        {
          "hour": 12,
          "count": 53
        },
        {
          "hour": 13,
          "count": 39
        },
        {
          "hour": 14,
          "count": 36
        },
        {
          "hour": 15,
          "count": 43
        },
        {
          "hour": 16,
          "count": 37
        },
        {
          "hour": 17,
          "count": 50
        },
        {
          "hour": 18,
          "count": 56
        },
        {
          "hour": 19,
          "count": 41
        },
        {
          "hour": 20,
          "count": 50
        },
        {
          "hour": 21,
          "count": 34
        },
        {
          "hour": 22,
          "count": 36
        },
        {
          "hour": 23,
          "count": 38
        }
      ]
    },
    {
      "product": "Takis",
      "total": 688,
      "unmet": 552,
      "requested": 136,
      "machinesStocking": 0,
      "topBuildings": [
        {
          "building": "Perkins Library",
          "count": 16
        },
        {
          "building": "Bryan Center",
          "count": 14
        },
        {
          "building": "Broadhead Center",
          "count": 13
        },
        {
          "building": "Levine Science Research Center",
          "count": 13
        },
        {
          "building": "Social Sciences Building",
          "count": 13
        },
        {
          "building": "Physics Building",
          "count": 11
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 19
        },
        {
          "hour": 1,
          "count": 24
        },
        {
          "hour": 2,
          "count": 14
        },
        {
          "hour": 3,
          "count": 2
        },
        {
          "hour": 4,
          "count": 3
        },
        {
          "hour": 5,
          "count": 3
        },
        {
          "hour": 6,
          "count": 7
        },
        {
          "hour": 7,
          "count": 21
        },
        {
          "hour": 8,
          "count": 30
        },
        {
          "hour": 9,
          "count": 32
        },
        {
          "hour": 10,
          "count": 29
        },
        {
          "hour": 11,
          "count": 46
        },
        {
          "hour": 12,
          "count": 46
        },
        {
          "hour": 13,
          "count": 43
        },
        {
          "hour": 14,
          "count": 33
        },
        {
          "hour": 15,
          "count": 31
        },
        {
          "hour": 16,
          "count": 44
        },
        {
          "hour": 17,
          "count": 44
        },
        {
          "hour": 18,
          "count": 44
        },
        {
          "hour": 19,
          "count": 42
        },
        {
          "hour": 20,
          "count": 47
        },
        {
          "hour": 21,
          "count": 35
        },
        {
          "hour": 22,
          "count": 32
        },
        {
          "hour": 23,
          "count": 17
        }
      ]
    },
    {
      "product": "Body Armor",
      "total": 617,
      "unmet": 0,
      "requested": 0,
      "machinesStocking": 6,
      "topBuildings": [
        {
          "building": "Perkins Library",
          "count": 68
        },
        {
          "building": "Levine Science Research Center",
          "count": 66
        },
        {
          "building": "Bryan Center",
          "count": 57
        },
        {
          "building": "Broadhead Center",
          "count": 57
        },
        {
          "building": "Nello L. Teer Building",
          "count": 42
        },
        {
          "building": "Randolph Residence Hall",
          "count": 39
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 15
        },
        {
          "hour": 1,
          "count": 32
        },
        {
          "hour": 2,
          "count": 20
        },
        {
          "hour": 3,
          "count": 2
        },
        {
          "hour": 4,
          "count": 2
        },
        {
          "hour": 5,
          "count": 3
        },
        {
          "hour": 6,
          "count": 8
        },
        {
          "hour": 7,
          "count": 13
        },
        {
          "hour": 8,
          "count": 30
        },
        {
          "hour": 9,
          "count": 22
        },
        {
          "hour": 10,
          "count": 33
        },
        {
          "hour": 11,
          "count": 32
        },
        {
          "hour": 12,
          "count": 27
        },
        {
          "hour": 13,
          "count": 32
        },
        {
          "hour": 14,
          "count": 26
        },
        {
          "hour": 15,
          "count": 36
        },
        {
          "hour": 16,
          "count": 39
        },
        {
          "hour": 17,
          "count": 39
        },
        {
          "hour": 18,
          "count": 39
        },
        {
          "hour": 19,
          "count": 47
        },
        {
          "hour": 20,
          "count": 39
        },
        {
          "hour": 21,
          "count": 24
        },
        {
          "hour": 22,
          "count": 33
        },
        {
          "hour": 23,
          "count": 24
        }
      ]
    },
    {
      "product": "Pop Tarts",
      "total": 579,
      "unmet": 0,
      "requested": 0,
      "machinesStocking": 27,
      "topBuildings": [
        {
          "building": "Perkins Library",
          "count": 85
        },
        {
          "building": "Levine Science Research Center",
          "count": 60
        },
        {
          "building": "Bryan Center",
          "count": 50
        },
        {
          "building": "Broadhead Center",
          "count": 45
        },
        {
          "building": "Physics Building",
          "count": 44
        },
        {
          "building": "Social Sciences Building",
          "count": 29
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 10
        },
        {
          "hour": 1,
          "count": 12
        },
        {
          "hour": 2,
          "count": 12
        },
        {
          "hour": 3,
          "count": 2
        },
        {
          "hour": 4,
          "count": 1
        },
        {
          "hour": 5,
          "count": 2
        },
        {
          "hour": 6,
          "count": 6
        },
        {
          "hour": 7,
          "count": 9
        },
        {
          "hour": 8,
          "count": 27
        },
        {
          "hour": 9,
          "count": 18
        },
        {
          "hour": 10,
          "count": 26
        },
        {
          "hour": 11,
          "count": 34
        },
        {
          "hour": 12,
          "count": 43
        },
        {
          "hour": 13,
          "count": 34
        },
        {
          "hour": 14,
          "count": 39
        },
        {
          "hour": 15,
          "count": 37
        },
        {
          "hour": 16,
          "count": 36
        },
        {
          "hour": 17,
          "count": 37
        },
        {
          "hour": 18,
          "count": 34
        },
        {
          "hour": 19,
          "count": 40
        },
        {
          "hour": 20,
          "count": 28
        },
        {
          "hour": 21,
          "count": 37
        },
        {
          "hour": 22,
          "count": 30
        },
        {
          "hour": 23,
          "count": 25
        }
      ]
    },
    {
      "product": "Pringles",
      "total": 571,
      "unmet": 0,
      "requested": 0,
      "machinesStocking": 5,
      "topBuildings": [
        {
          "building": "Levine Science Research Center",
          "count": 76
        },
        {
          "building": "Perkins Library",
          "count": 65
        },
        {
          "building": "Bryan Center",
          "count": 53
        },
        {
          "building": "Broadhead Center",
          "count": 44
        },
        {
          "building": "Physics Building",
          "count": 34
        },
        {
          "building": "Nello L. Teer Building",
          "count": 33
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 18
        },
        {
          "hour": 1,
          "count": 24
        },
        {
          "hour": 2,
          "count": 20
        },
        {
          "hour": 3,
          "count": 1
        },
        {
          "hour": 4,
          "count": 1
        },
        {
          "hour": 5,
          "count": 2
        },
        {
          "hour": 6,
          "count": 9
        },
        {
          "hour": 7,
          "count": 18
        },
        {
          "hour": 8,
          "count": 22
        },
        {
          "hour": 9,
          "count": 24
        },
        {
          "hour": 10,
          "count": 32
        },
        {
          "hour": 11,
          "count": 33
        },
        {
          "hour": 12,
          "count": 35
        },
        {
          "hour": 13,
          "count": 40
        },
        {
          "hour": 14,
          "count": 24
        },
        {
          "hour": 15,
          "count": 33
        },
        {
          "hour": 16,
          "count": 31
        },
        {
          "hour": 17,
          "count": 42
        },
        {
          "hour": 18,
          "count": 33
        },
        {
          "hour": 19,
          "count": 37
        },
        {
          "hour": 20,
          "count": 30
        },
        {
          "hour": 21,
          "count": 18
        },
        {
          "hour": 22,
          "count": 27
        },
        {
          "hour": 23,
          "count": 17
        }
      ]
    },
    {
      "product": "Liquid Death",
      "total": 570,
      "unmet": 477,
      "requested": 93,
      "machinesStocking": 0,
      "topBuildings": [
        {
          "building": "Bryan Center",
          "count": 13
        },
        {
          "building": "Perkins Library",
          "count": 13
        },
        {
          "building": "Levine Science Research Center",
          "count": 8
        },
        {
          "building": "Wilson Recreation Center",
          "count": 6
        },
        {
          "building": "Broadhead Center",
          "count": 6
        },
        {
          "building": "Allen Building",
          "count": 5
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 19
        },
        {
          "hour": 1,
          "count": 19
        },
        {
          "hour": 2,
          "count": 8
        },
        {
          "hour": 3,
          "count": 1
        },
        {
          "hour": 4,
          "count": 1
        },
        {
          "hour": 5,
          "count": 0
        },
        {
          "hour": 6,
          "count": 7
        },
        {
          "hour": 7,
          "count": 16
        },
        {
          "hour": 8,
          "count": 21
        },
        {
          "hour": 9,
          "count": 24
        },
        {
          "hour": 10,
          "count": 18
        },
        {
          "hour": 11,
          "count": 37
        },
        {
          "hour": 12,
          "count": 37
        },
        {
          "hour": 13,
          "count": 40
        },
        {
          "hour": 14,
          "count": 25
        },
        {
          "hour": 15,
          "count": 33
        },
        {
          "hour": 16,
          "count": 30
        },
        {
          "hour": 17,
          "count": 45
        },
        {
          "hour": 18,
          "count": 49
        },
        {
          "hour": 19,
          "count": 32
        },
        {
          "hour": 20,
          "count": 33
        },
        {
          "hour": 21,
          "count": 22
        },
        {
          "hour": 22,
          "count": 27
        },
        {
          "hour": 23,
          "count": 26
        }
      ]
    },
    {
      "product": "Sour Patch Kids",
      "total": 430,
      "unmet": 0,
      "requested": 0,
      "machinesStocking": 5,
      "topBuildings": [
        {
          "building": "Perkins Library",
          "count": 60
        },
        {
          "building": "Levine Science Research Center",
          "count": 39
        },
        {
          "building": "Bryan Center",
          "count": 36
        },
        {
          "building": "Nello L. Teer Building",
          "count": 30
        },
        {
          "building": "Broadhead Center",
          "count": 27
        },
        {
          "building": "Few Quad",
          "count": 26
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 16
        },
        {
          "hour": 1,
          "count": 13
        },
        {
          "hour": 2,
          "count": 12
        },
        {
          "hour": 3,
          "count": 2
        },
        {
          "hour": 4,
          "count": 1
        },
        {
          "hour": 5,
          "count": 1
        },
        {
          "hour": 6,
          "count": 4
        },
        {
          "hour": 7,
          "count": 12
        },
        {
          "hour": 8,
          "count": 20
        },
        {
          "hour": 9,
          "count": 19
        },
        {
          "hour": 10,
          "count": 27
        },
        {
          "hour": 11,
          "count": 25
        },
        {
          "hour": 12,
          "count": 35
        },
        {
          "hour": 13,
          "count": 25
        },
        {
          "hour": 14,
          "count": 22
        },
        {
          "hour": 15,
          "count": 19
        },
        {
          "hour": 16,
          "count": 21
        },
        {
          "hour": 17,
          "count": 26
        },
        {
          "hour": 18,
          "count": 28
        },
        {
          "hour": 19,
          "count": 26
        },
        {
          "hour": 20,
          "count": 20
        },
        {
          "hour": 21,
          "count": 19
        },
        {
          "hour": 22,
          "count": 27
        },
        {
          "hour": 23,
          "count": 10
        }
      ]
    },
    {
      "product": "Muscle Milk",
      "total": 416,
      "unmet": 317,
      "requested": 99,
      "machinesStocking": 0,
      "topBuildings": [
        {
          "building": "Broadhead Center",
          "count": 14
        },
        {
          "building": "Perkins Library",
          "count": 12
        },
        {
          "building": "Levine Science Research Center",
          "count": 11
        },
        {
          "building": "Nello L. Teer Building",
          "count": 7
        },
        {
          "building": "Wilson Recreation Center",
          "count": 7
        },
        {
          "building": "Physics Building",
          "count": 6
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 15
        },
        {
          "hour": 1,
          "count": 5
        },
        {
          "hour": 2,
          "count": 13
        },
        {
          "hour": 3,
          "count": 1
        },
        {
          "hour": 4,
          "count": 0
        },
        {
          "hour": 5,
          "count": 2
        },
        {
          "hour": 6,
          "count": 4
        },
        {
          "hour": 7,
          "count": 5
        },
        {
          "hour": 8,
          "count": 18
        },
        {
          "hour": 9,
          "count": 23
        },
        {
          "hour": 10,
          "count": 29
        },
        {
          "hour": 11,
          "count": 22
        },
        {
          "hour": 12,
          "count": 21
        },
        {
          "hour": 13,
          "count": 24
        },
        {
          "hour": 14,
          "count": 15
        },
        {
          "hour": 15,
          "count": 16
        },
        {
          "hour": 16,
          "count": 35
        },
        {
          "hour": 17,
          "count": 20
        },
        {
          "hour": 18,
          "count": 33
        },
        {
          "hour": 19,
          "count": 30
        },
        {
          "hour": 20,
          "count": 20
        },
        {
          "hour": 21,
          "count": 29
        },
        {
          "hour": 22,
          "count": 25
        },
        {
          "hour": 23,
          "count": 11
        }
      ]
    },
    {
      "product": "Goldfish",
      "total": 411,
      "unmet": 0,
      "requested": 0,
      "machinesStocking": 5,
      "topBuildings": [
        {
          "building": "Bryan Center",
          "count": 47
        },
        {
          "building": "Levine Science Research Center",
          "count": 41
        },
        {
          "building": "Perkins Library",
          "count": 36
        },
        {
          "building": "Physics Building",
          "count": 29
        },
        {
          "building": "Broadhead Center",
          "count": 26
        },
        {
          "building": "Bell Tower Residence Hall",
          "count": 24
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 7
        },
        {
          "hour": 1,
          "count": 9
        },
        {
          "hour": 2,
          "count": 15
        },
        {
          "hour": 3,
          "count": 0
        },
        {
          "hour": 4,
          "count": 0
        },
        {
          "hour": 5,
          "count": 1
        },
        {
          "hour": 6,
          "count": 7
        },
        {
          "hour": 7,
          "count": 12
        },
        {
          "hour": 8,
          "count": 10
        },
        {
          "hour": 9,
          "count": 19
        },
        {
          "hour": 10,
          "count": 18
        },
        {
          "hour": 11,
          "count": 30
        },
        {
          "hour": 12,
          "count": 25
        },
        {
          "hour": 13,
          "count": 14
        },
        {
          "hour": 14,
          "count": 22
        },
        {
          "hour": 15,
          "count": 17
        },
        {
          "hour": 16,
          "count": 37
        },
        {
          "hour": 17,
          "count": 23
        },
        {
          "hour": 18,
          "count": 34
        },
        {
          "hour": 19,
          "count": 29
        },
        {
          "hour": 20,
          "count": 20
        },
        {
          "hour": 21,
          "count": 22
        },
        {
          "hour": 22,
          "count": 24
        },
        {
          "hour": 23,
          "count": 16
        }
      ]
    },
    {
      "product": "Gushers",
      "total": 391,
      "unmet": 0,
      "requested": 0,
      "machinesStocking": 46,
      "topBuildings": [
        {
          "building": "Perkins Library",
          "count": 52
        },
        {
          "building": "Levine Science Research Center",
          "count": 37
        },
        {
          "building": "Bryan Center",
          "count": 33
        },
        {
          "building": "Broadhead Center",
          "count": 30
        },
        {
          "building": "Physics Building",
          "count": 27
        },
        {
          "building": "Bell Tower Residence Hall",
          "count": 23
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 19
        },
        {
          "hour": 1,
          "count": 7
        },
        {
          "hour": 2,
          "count": 7
        },
        {
          "hour": 3,
          "count": 3
        },
        {
          "hour": 4,
          "count": 1
        },
        {
          "hour": 5,
          "count": 4
        },
        {
          "hour": 6,
          "count": 2
        },
        {
          "hour": 7,
          "count": 11
        },
        {
          "hour": 8,
          "count": 18
        },
        {
          "hour": 9,
          "count": 18
        },
        {
          "hour": 10,
          "count": 24
        },
        {
          "hour": 11,
          "count": 14
        },
        {
          "hour": 12,
          "count": 25
        },
        {
          "hour": 13,
          "count": 13
        },
        {
          "hour": 14,
          "count": 25
        },
        {
          "hour": 15,
          "count": 20
        },
        {
          "hour": 16,
          "count": 22
        },
        {
          "hour": 17,
          "count": 20
        },
        {
          "hour": 18,
          "count": 24
        },
        {
          "hour": 19,
          "count": 32
        },
        {
          "hour": 20,
          "count": 31
        },
        {
          "hour": 21,
          "count": 18
        },
        {
          "hour": 22,
          "count": 18
        },
        {
          "hour": 23,
          "count": 15
        }
      ]
    },
    {
      "product": "Kombucha",
      "total": 347,
      "unmet": 277,
      "requested": 70,
      "machinesStocking": 0,
      "topBuildings": [
        {
          "building": "Perkins Library",
          "count": 13
        },
        {
          "building": "Levine Science Research Center",
          "count": 12
        },
        {
          "building": "Bryan Center",
          "count": 7
        },
        {
          "building": "Physics Building",
          "count": 6
        },
        {
          "building": "Broadhead Center",
          "count": 5
        },
        {
          "building": "Trinity Residence Hall",
          "count": 4
        }
      ],
      "byHour": [
        {
          "hour": 0,
          "count": 9
        },
        {
          "hour": 1,
          "count": 7
        },
        {
          "hour": 2,
          "count": 9
        },
        {
          "hour": 3,
          "count": 1
        },
        {
          "hour": 4,
          "count": 0
        },
        {
          "hour": 5,
          "count": 3
        },
        {
          "hour": 6,
          "count": 5
        },
        {
          "hour": 7,
          "count": 13
        },
        {
          "hour": 8,
          "count": 10
        },
        {
          "hour": 9,
          "count": 16
        },
        {
          "hour": 10,
          "count": 20
        },
        {
          "hour": 11,
          "count": 14
        },
        {
          "hour": 12,
          "count": 17
        },
        {
          "hour": 13,
          "count": 18
        },
        {
          "hour": 14,
          "count": 16
        },
        {
          "hour": 15,
          "count": 19
        },
        {
          "hour": 16,
          "count": 30
        },
        {
          "hour": 17,
          "count": 19
        },
        {
          "hour": 18,
          "count": 30
        },
        {
          "hour": 19,
          "count": 21
        },
        {
          "hour": 20,
          "count": 16
        },
        {
          "hour": 21,
          "count": 13
        },
        {
          "hour": 22,
          "count": 22
        },
        {
          "hour": 23,
          "count": 19
        }
      ]
    }
  ],
  "recommendations": [
    {
      "type": "add_requested",
      "priority": 1216,
      "text": "\"Prime\" was directly requested 216 times and isn't stocked here — a clear add."
    },
    {
      "type": "add_requested",
      "priority": 1216,
      "text": "\"Alani\" was directly requested 216 times and isn't stocked here — a clear add."
    },
    {
      "type": "add_product",
      "priority": 1163,
      "text": "Add \"Prime\" to the catalog — searched 1163 times with no in-stock result anywhere on campus."
    },
    {
      "type": "add_requested",
      "priority": 1136,
      "text": "\"Takis\" was directly requested 136 times and isn't stocked here — a clear add."
    },
    {
      "type": "add_requested",
      "priority": 1118,
      "text": "\"Red Bull\" was directly requested 118 times and isn't stocked here — a clear add."
    },
    {
      "type": "add_requested",
      "priority": 1099,
      "text": "\"Muscle Milk\" was directly requested 99 times and isn't stocked here — a clear add."
    },
    {
      "type": "add_requested",
      "priority": 1093,
      "text": "\"Liquid Death\" was directly requested 93 times and isn't stocked here — a clear add."
    },
    {
      "type": "add_requested",
      "priority": 1070,
      "text": "\"Kombucha\" was directly requested 70 times and isn't stocked here — a clear add."
    }
  ]
};
